language: python

# for container-y googdness:
sudo: false

env:
  - DB=sqlite
  - DB=mysql
  - DB=postgres

python:
  - "3.4"
  - "2.7"

# command to install dependencies
install: "pip install -Ue .[test,build]"

before_script:
  - sh -c "if [ $DB = 'postgres' ]; then psql -c 'create database test' -U postgres; fi"
  - sh -c "if [ $DB = 'mysql' ]; then mysql -e 'create database test'; fi"

# command to run tests, e.g. python setup.py test
script:
  - sh -c "if [ $DB = 'sqlite' ]; then export DB_URL=; nosetests --with-cov --cov=mortar_rdb; fi;"
  - sh -c "if [ $DB = 'postgres' ]; then export DB_URL='postgres://postgres@localhost/test'; nosetests --with-cov --cov=mortar_rdb; fi;"
  - sh -c "if [ $DB = 'mysql' ]; then export DB_URL='mysql+mysqlconnector://travis@localhost/test'; nosetests --with-cov --cov=mortar_rdb; fi; "

after_success:
  - coveralls

deploy:
  provider: pypi
  user: chrisw
  password:
    secure: QrmUWPegJzGIYGI8XGY7ztjHTbpMgVDLNV6f9fjjAoo8efOubJh/BASjWD3ESPlIo1j5tGCcSRP2MN1+30zBxq7a7oiCnthISx42DP6Ih+wLHFCu7uBm12AH96hIOQUAtQotNSwB9dJAJIKKom7xkrV/nStjbcqC7hosTZlTy6o=
  on:
    tags: true
    repo: Mortar/mortar_rdb
    python: "3.4"
  skip_cleanup: true
  distributions: "sdist bdist_wheel"
