language: python

# for container-y googdness:
sudo: false

env:
  - DB=sqlite
  - DB=mysql
  - DB=postgres

python:
  - "3.6"
  - "2.7"

# command to install dependencies
install:
  - "pip install --upgrade pip"
  - sh -c "pip install -Ue .[test,build]"
  - sh -c "if [ $DB = 'postgres' ]; then pip install psycopg2; fi"
  - sh -c "if [ $DB = 'mysql' ]; then pip install PyMySQL; fi"

before_script:
  - sh -c "if [ $DB = 'postgres' ]; then psql -c 'create database test' -U postgres; fi"
  - sh -c "if [ $DB = 'mysql' ]; then mysql -e 'create database test' && mysql -e 'GRANT ALL ON test.* TO 'travis'@'localhost';'; fi"
# command to run tests, e.g. python setup.py test
script:
  - sh -c "if [ $DB = 'sqlite' ]; then export DB_URL=; coverage run --source mortar_rdb -m pytest; fi;"
  - sh -c "if [ $DB = 'postgres' ]; then export DB_URL='postgres://postgres@localhost/test'; coverage run --source mortar_rdb -m pytest; fi;"
  - sh -c "if [ $DB = 'mysql' ]; then export DB_URL='mysql+pymysql://travis@localhost/test'; coverage run --source mortar_rdb -m pytest; fi; "

after_success:
  - coveralls

deploy:
  provider: pypi
  user: chrisw
  password:
    secure: dMB0Gq9TMVZdNwYjq9fhIjCa5irrmH8dAha8VQrUMTbJZwdCJb9n8ODRUGsP/fPhYwtnQKiDMKJtHBFRJ71GxSxBNYLGrrVayHes6goGwkxznMBDx6OjROFh90rvtNp3QPaqSZid5md6hAqfWf90wRelWeFkqf2hR/mW10oDvlw=
  on:
    tags: true
    repo: Mortar/mortar_rdb
    python: "3.6"
    condition: $DB = sqlite
  skip_cleanup: true
  distributions: "sdist bdist_wheel"
