version: 2.1

#orbs:
#  python: cjw296/python-ci@1.0.2
#
orbs:
  python:
    commands:
      run-with-coverage:
        parameters:
          command:
            type: string
        steps:
          - run:
              name: "Run Tests"
              command: |
                python --version
                mkdir -p coverage_output
                export COVERAGE_FILE=coverage_output/.coverage.$CIRCLE_BUILD_NUM
                << parameters.command >>
          - persist_to_workspace:
              root: coverage_output
              paths:
                - .coverage.*
      pip-run-tests:
        parameters:
          prepare:
            type: steps
            default: []
          command:
            type: string
            default: pytest --cov
          extra_packages:
            type: string
            default: ""
        steps:
          - checkout
          - run:
              name: "Install Project"
              command: "sudo pip install << parameters.extra_packages >> -e .[test]"
          - steps: << parameters.prepare >>
          - run-with-coverage:
              command: << parameters.command >>
#    jobs:
#      pip-run-tests:
#        parameters:
#          image:
#            type: string
#          command:
#            type: string
#            default: pytest --cov
#          prepare:
#            type: steps
#            default: []
#        docker:
#          - image: << parameters.image >>
#        steps:
#          - checkout
#          - run:
#              name: "Install Project"
#              command: sudo pip install -e .[test]
#          - steps: << parameters.prepare >>
#          - run-with-coverage:
#              command: << parameters.command >>

jobs:
  sqlite:
    parameters:
      python:
        type: string
    docker:
      - image: circleci/python:<< parameters.python >>
        environment:
          DB_URL: ""
    steps:
      - python/pip-run-tests
  postgres:
    parameters:
      python:
        type: string
    docker:
      - image: circleci/python:<< parameters.python >>
        environment:
          DB_URL: postgresql://postgres@localhost/circle_test
      - image: circleci/postgres:11.2-alpine-ram
    steps:
      - python/pip-run-tests:
          extra_packages: psycopg2
  mysql:
    parameters:
      python:
        type: string
    docker:
      - image: circleci/python:<< parameters.python >>
        environment:
          DB_URL: mysql+pymysql://root@localhost/circle_test
      - image: circleci/mysql:8.0.3-ram
    steps:
      - python/pip-run-tests:
          extra_packages: PyMySQL

common: &common
  jobs:
    - sqlite:
        name: python37-sqlite
        python: '3.7'
    - postgres:
        name: python37-postgres
        python: '3.7'
    - mysql:
        name: python37-mysql
        python: '3.7'

#    - python/coverage:
#        name: coverage
#        requires:
#          - python27
#          - python36
#          - python37
#
#    - python/release:
#        name: release
#        requires:
#          - coverage
#        filters:
#          branches:
#            only: master

workflows:
  push:
    <<: *common
#  periodic:
#    <<: *common
#    triggers:
#      - schedule:
#          cron: "0 0 * * 4"
#          filters:
#            branches:
#              only: master
